import type { Severity } from "./format";

export type ModuleCatalog = {
  path: string;
  group: string;
  title: string;
  desc: string;
  kpis: { label: string; value: string; sub: string; tone: Severity }[];
  filters: string[];
  tabs?: string[];
  tableTitle: string;
  columns: string[];
  rows: (string | number)[][];
  statusCol?: number; // index of status column for tone rendering
  tabFilterCols?: number[]; // columns tabs match against (row matches if ANY listed column matches); defaults to [statusCol]
  actions?: string[];
  primaryAction?: string;
  layout?: "table" | "cards"; // default "table"
  cardConfig?: {
    titleCol: number;
    subtitleCol?: number;
    statCols?: { label: string; col: number }[];
  };
  dateRangeFilters?: string[]; // filter labels rendered as a from/to date-input pair instead of a select
};

const F = {
  base: ["Date Range", "Branch", "Status", "Search"],
  ext: ["Date Range", "Branch", "Terminal", "Cashier", "Status", "Search"],
};

export const catalog: ModuleCatalog[] = [
  /* ========== OPERATE ========== */
  /* /operate/orders, /operate/customers, /operate/cashier-workspace and /operate/cashier-shift now
     render dedicated components (src/components/buildpos/pos/) instead of this generic catalog. */
  {
    path: "/operate/control-tower",
    group: "Operate",
    title: "Control Tower",
    desc: "Supervisor view of branches, terminals, queues and critical alerts.",
    kpis: [
      { label: "Active Branches", value: "5 / 5", sub: "All online", tone: "success" },
      { label: "Active Terminals", value: "23 / 26", sub: "1 offline · 2 idle", tone: "warning" },
      { label: "Queue Length", value: "14", sub: "3 branches busy", tone: "info" },
      { label: "Critical Alerts", value: "3", sub: "Requires escalation", tone: "critical" },
      { label: "Pending Approvals", value: "8", sub: "Discount / Refund", tone: "warning" },
      { label: "Sync Backlog", value: "24 events", sub: "Clearing", tone: "info" },
      { label: "Delivery Overdue", value: "2", sub: "Dispatch alert", tone: "critical" },
      { label: "ZATCA Failures", value: "1", sub: "INV-2026-00891", tone: "critical" },
    ],
    filters: ["Branch", "Severity", "Module"],
    tableTitle: "Live Operational Alerts",
    columns: ["Time", "Branch", "Terminal", "Module", "Alert", "Owner", "SLA", "Status"],
    rows: [
      [
        "02:44 PM",
        "Riyadh Main",
        "POS-03",
        "Network",
        "Terminal offline 45 min",
        "IT Support",
        "15 min",
        "Critical",
      ],
      [
        "02:41 PM",
        "Riyadh Main",
        "POS-01",
        "ZATCA",
        "Invoice INV-2026-00891 failed",
        "Finance Manager",
        "30 min",
        "Critical",
      ],
      [
        "02:33 PM",
        "Jeddah",
        "—",
        "Delivery",
        "DO-1017 overdue by 1h",
        "Dispatch",
        "60 min",
        "Warning",
      ],
      [
        "02:22 PM",
        "Riyadh Main",
        "POS-04",
        "Cashier Shift",
        "Cash variance -40 ر.س",
        "Store Manager",
        "30 min",
        "Warning",
      ],
      [
        "02:10 PM",
        "Dammam",
        "—",
        "Stock",
        "OPC Cement below reorder",
        "Inventory",
        "4 hr",
        "Critical",
      ],
    ],
    statusCol: 7,
    actions: ["Acknowledge", "Escalate", "Drill Down"],
  },

  /* ========== STOCK ========== */
  {
    path: "/stock/stocks",
    group: "Stock",
    title: "Inventory & Stock",
    desc: "Warehouse-held bulk stock — on-hand, reserved, quarantine and low-stock alerts, independent of what's sellable on a branch's shop floor (see Branch Stock).",
    kpis: [
      { label: "Available", value: "12,850", sub: "SKUs in stock", tone: "success" },
      { label: "Reserved", value: "1,240", sub: "Contractor / Delivery", tone: "info" },
      { label: "Quarantine", value: "27", sub: "Damage / Recall", tone: "warning" },
      { label: "Low Stock", value: "34", sub: "12 critical", tone: "critical" },
      { label: "Out of Stock", value: "11", sub: "3 top-sellers", tone: "critical" },
      { label: "Stock Value", value: "1,284,500 ر.س", sub: "At cost", tone: "info" },
      { label: "In Transit", value: "9", sub: "Branch transfers", tone: "info" },
      { label: "Adjustments Today", value: "4", sub: "1 pending approval", tone: "warning" },
    ],
    // Warehouse stock is a live snapshot with no date or branch column of its own (the branch is
    // a property of the warehouse) — F.base's "Date Range"/"Branch" had nothing to filter here.
    filters: ["Search", "Item", "Category", "Warehouse", "Availability"],
    tableTitle: "Stock Availability",
    columns: [
      "SKU",
      "Product",
      "Category",
      "Warehouse",
      "On Hand",
      "Reserved",
      "Available",
      "Reorder",
      "Value (ر.س)",
      "Status",
    ],
    rows: [
      [
        "CEM-OPC-50KG",
        "OPC Cement 50KG",
        "Cement",
        "Riyadh Main",
        42,
        20,
        22,
        100,
        "1,890",
        "Critical",
      ],
      ["TILE-GRY-60X60", "Grey Tile 60x60", "Tiles", "Jeddah", 12, 4, 8, 50, "5,200", "Critical"],
      [
        "STEEL-RBR-12MM",
        "Steel Rebar 12MM",
        "Steel",
        "Riyadh Main",
        22,
        6,
        16,
        40,
        "42,800",
        "Low",
      ],
      [
        "PAINT-WHT-20L",
        "White Paint 20L",
        "Paint",
        "Riyadh Main",
        8,
        3,
        5,
        30,
        "1,120",
        "Critical",
      ],
      ["PVC-PIPE-2IN", "PVC Pipe 2 Inch", "Plumbing", "Dammam", 40, 6, 34, 80, "1,020", "Low"],
      [
        "ELEC-CBL-2.5MM",
        "Electric Cable 2.5MM",
        "Electrical",
        "Riyadh Main",
        120,
        30,
        90,
        250,
        "3,240",
        "Low",
      ],
      ["GLASS-6MM-CLR", "Clear Glass 6MM", "Glass", "Jeddah", 62, 0, 62, 20, "18,600", "Healthy"],
    ],
    statusCol: 9,
    actions: ["New Adjustment", "Export"],
    primaryAction: "New Adjustment",
  },
  {
    path: "/stock/branch-stock",
    group: "Stock",
    title: "Branch Stock",
    desc: "Each branch's own shop-floor on-hand quantity — what's actually sellable right now, independent of warehouse bulk stock.",
    kpis: [
      { label: "Healthy", value: "—", sub: "Loading…", tone: "success" },
      { label: "Low Stock", value: "—", sub: "Approaching reorder", tone: "warning" },
      { label: "Critical / Out", value: "—", sub: "Can't be sold right now", tone: "critical" },
      { label: "Stock Value", value: "—", sub: "At cost, all branches", tone: "info" },
    ],
    filters: ["Search", "Item", "Category", "Branch", "Availability"],
    tableTitle: "Branch Stock Availability",
    columns: [
      "SKU",
      "Product",
      "Category",
      "Branch",
      "On Hand",
      "Reserved",
      "Available",
      "Reorder",
      "Value (ر.س)",
      "Status",
    ],
    rows: [],
    statusCol: 9,
    actions: ["Export"],
  },
  {
    path: "/stock/movements",
    group: "Stock",
    title: "Stock Movements",
    desc: "Every event that changed a branch's sellable stock — sales, returns, damage, transfers, PO receipts, and adjustments.",
    kpis: [
      { label: "Sold", value: "—", sub: "Loading…", tone: "info" },
      { label: "Returned", value: "—", sub: "Restocked to sellable", tone: "success" },
      { label: "Damaged", value: "—", sub: "Quarantined", tone: "critical" },
      { label: "Adjusted", value: "—", sub: "Stocktake variance", tone: "warning" },
    ],
    filters: ["Branch", "Type", "Search"],
    dateRangeFilters: ["Date"],
    tableTitle: "Movement Ledger",
    columns: ["Date", "Type", "SKU", "Product", "Branch", "Qty", "Direction", "Reference"],
    rows: [],
    statusCol: 6,
    actions: ["Export"],
  },
  {
    path: "/stock/inventory",
    group: "Stock",
    title: "Inventory",
    desc: "SKU master, categories, UOM engine, attributes and pricing metadata.",
    kpis: [
      { label: "Active SKUs", value: "6,412", sub: "128 new this month", tone: "success" },
      { label: "Inactive SKUs", value: "184", sub: "Discontinued", tone: "muted" },
      { label: "Low Stock SKUs", value: "34", sub: "Reorder now", tone: "warning" },
      { label: "Missing Barcode", value: "22", sub: "Blocks POS scan", tone: "critical" },
      { label: "Missing UOM", value: "9", sub: "Blocks sale", tone: "critical" },
      { label: "Non-Returnable", value: "148", sub: "Paint, chemicals", tone: "info" },
      { label: "Bundle Items", value: "62", sub: "12 expired", tone: "info" },
      { label: "Price Changes", value: "18", sub: "Last 7 days", tone: "info" },
    ],
    // The product master is a catalog, not a transaction log — no date or branch dimension. Status
    // stays (it's a real column); "Supplier" doesn't exist on this table and is dropped.
    filters: ["Search", "Category", "Brand", "UOM Type", "VAT Rate", "Status"],
    tableTitle: "Product Master",
    columns: [
      "SKU",
      "Barcode",
      "Name EN/AR",
      "Category",
      "Brand",
      "Price (ر.س)",
      "VAT",
      "Stock UOM",
      "Selling UOMs",
      "Stock",
      "Status",
    ],
    rows: [
      [
        "CEM-OPC-50KG",
        "6281100011234",
        "OPC Cement 50KG / أسمنت",
        "Cement",
        "Al Noor",
        "22.50",
        "15%",
        "Bag",
        "Bag, Pallet(50)",
        42,
        "Active",
      ],
      [
        "TILE-GRY-60X60",
        "6281100022345",
        "Grey Tile 60x60 / بلاط رمادي",
        "Tiles",
        "Saudi Tiles",
        "44.00",
        "15%",
        "Box",
        "Box, m²",
        12,
        "Active",
      ],
      [
        "STEEL-RBR-12MM",
        "6281100033456",
        "Rebar 12MM / حديد تسليح",
        "Steel",
        "Gulf Steel",
        "1,950.00",
        "15%",
        "Bundle",
        "Bundle, Ton",
        22,
        "Active",
      ],
      [
        "PAINT-WHT-20L",
        "6281100044567",
        "White Paint 20L / دهان أبيض",
        "Paint",
        "ColorPro",
        "220.00",
        "15%",
        "Can",
        "Can",
        8,
        "Active",
      ],
      [
        "GLASS-6MM-CLR",
        "6281100055678",
        "Clear Glass 6MM / زجاج شفاف",
        "Glass",
        "SaudiGlass",
        "180.00",
        "15%",
        "m²",
        "m², Panel",
        62,
        "Non-Returnable",
      ],
      [
        "TOOL-DRL-18V",
        "6281100066789",
        "Cordless Drill 18V / مثقاب",
        "Tools",
        "PowerMax",
        "540.00",
        "15%",
        "Piece",
        "Piece",
        34,
        "Serial-Tracked",
      ],
    ],
    statusCol: 10,
    actions: ["Add SKU", "Add Product with Variants", "Print Barcodes", "Print Labels", "Export"],
    primaryAction: "Add SKU",
  },
  {
    path: "/stock/variant-groups",
    group: "Stock",
    title: "Variant Groups",
    desc: "Group related SKUs (e.g. Steel Rebar 12MM/16MM) into one browsable family for POS/catalog.",
    kpis: [
      { label: "Variant Groups", value: "1", sub: "2 SKUs grouped", tone: "info" },
      { label: "Empty Groups", value: "0", sub: "No SKUs linked yet", tone: "success" },
    ],
    filters: ["Search", "Category", "Status"],
    tableTitle: "Variant Groups",
    columns: ["Code", "Name EN/AR", "Category", "Variants", "Status"],
    rows: [["STEEL-RBR", "Steel Rebar / حديد التسليح", "Steel", 2, "Active"]],
    statusCol: 4,
    actions: ["Add Group", "Export"],
    primaryAction: "Add Group",
  },
  {
    path: "/stock/expiry",
    group: "Stock",
    title: "Expiry & Material Validity",
    desc: "Batch-sensitive materials: paint, adhesives, chemicals, cement additives, sealants.",
    kpis: [
      { label: "Batch-Tracked SKUs", value: "412", sub: "9 categories", tone: "info" },
      { label: "Expiring ≤ 30 days", value: "18", sub: "Move to promo", tone: "warning" },
      { label: "Expiring ≤ 7 days", value: "7", sub: "Sell first", tone: "critical" },
      { label: "Expired", value: "3", sub: "Write-off pending", tone: "critical" },
      { label: "Write-Off Value", value: "4,820 ر.س", sub: "This month", tone: "warning" },
      { label: "Quarantine", value: "12", sub: "QC review", tone: "warning" },
      { label: "Batches Received", value: "9", sub: "This week", tone: "info" },
      { label: "Auto-Alerts", value: "On", sub: "30/15/7 days", tone: "success" },
    ],
    filters: ["Search", "Item", "Warehouse", "Days to Expiry", "Status"],
    dateRangeFilters: ["Expires"],
    tableTitle: "Expiry & Batch Ledger",
    columns: [
      "SKU",
      "Product",
      "Batch",
      "Received",
      "Expires",
      "Days Left",
      "Qty",
      "Location",
      "Status",
    ],
    rows: [
      [
        "PAINT-WHT-20L",
        "White Paint 20L",
        "B-2026-041",
        "12 Feb 2026",
        "15 Jul 2026",
        13,
        4,
        "Riyadh Main",
        "Expiring",
      ],
      [
        "ADH-TILE-5KG",
        "Tile Adhesive 5KG",
        "B-2026-072",
        "02 Apr 2026",
        "05 Jul 2026",
        3,
        22,
        "Jeddah",
        "Critical",
      ],
      [
        "CHEM-WPROOF-10L",
        "Waterproof Chem 10L",
        "B-2026-018",
        "05 Jan 2026",
        "01 Jul 2026",
        -1,
        6,
        "Riyadh Main",
        "Expired",
      ],
      [
        "SEAL-SILC-300ML",
        "Silicone Sealant 300ML",
        "B-2026-088",
        "22 May 2026",
        "22 Nov 2026",
        143,
        84,
        "Dammam",
        "Healthy",
      ],
      [
        "ADD-CEM-1KG",
        "Cement Additive 1KG",
        "B-2026-055",
        "10 Mar 2026",
        "10 Aug 2026",
        39,
        40,
        "Makkah",
        "Monitor",
      ],
    ],
    statusCol: 8,
    actions: ["Add Batch", "Export"],
    primaryAction: "Add Batch",
  },
  {
    path: "/stock/warehouses",
    group: "Stock",
    title: "Warehouses",
    desc: "Warehouse and bin/aisle setup, reservations and dispatch handoff.",
    kpis: [
      { label: "Warehouses", value: "7", sub: "5 branch · 2 central", tone: "info" },
      { label: "Bins/Locations", value: "1,842", sub: "94% mapped", tone: "success" },
      { label: "Utilization", value: "78%", sub: "Riyadh CW: 92%", tone: "warning" },
      { label: "Reservations", value: "1,240", sub: "For 34 orders", tone: "info" },
      { label: "Dispatch Ready", value: "18", sub: "Awaiting pickup", tone: "info" },
      { label: "Cycle Counts", value: "6", sub: "Due this week", tone: "warning" },
      { label: "Discrepancies", value: "4", sub: "Under review", tone: "warning" },
      { label: "Value Held", value: "4,180,500 ر.س", sub: "All warehouses", tone: "info" },
    ],
    filters: ["Search", "Branch", "Type", "Status"],
    tableTitle: "Warehouse Master",
    columns: [
      "Code",
      "Name",
      "Branch",
      "Type",
      "Bins",
      "Utilization",
      "Reservations",
      "Dispatch Ready",
      "Status",
    ],
    rows: [
      [
        "WH-RUH-CW",
        "Riyadh Central Warehouse",
        "Riyadh Main",
        "Central",
        620,
        "92%",
        480,
        12,
        "Active",
      ],
      ["WH-RUH-BR", "Riyadh Branch Store", "Riyadh Main", "Branch", 210, "68%", 180, 3, "Active"],
      ["WH-JED-CW", "Jeddah Central", "Jeddah", "Central", 480, "74%", 320, 2, "Active"],
      ["WH-DMM-BR", "Dammam Branch Store", "Dammam", "Branch", 240, "58%", 140, 1, "Active"],
      ["WH-MAK-BR", "Makkah Branch Store", "Makkah", "Branch", 180, "82%", 90, 0, "Active"],
      ["WH-MED-BR", "Madinah Branch Store", "Madinah", "Branch", 112, "48%", 30, 0, "Active"],
    ],
    statusCol: 8,
    actions: ["Add Warehouse", "Bin Setup", "Transfer", "Cycle Count"],
    primaryAction: "Add Warehouse",
  },
  {
    path: "/stock/transfers",
    group: "Stock",
    title: "Stock Transfers",
    desc: "Branch-to-branch and warehouse-to-branch stock movement.",
    tabs: ["All", "Draft", "Pending Approval", "Approved", "In Transit", "Received", "Cancelled"],
    kpis: [
      { label: "Open Transfers", value: "9", sub: "3 in transit", tone: "info" },
      { label: "Received Today", value: "6", sub: "42 SKUs", tone: "success" },
      { label: "Discrepancies", value: "1", sub: "Short or over-received", tone: "critical" },
      { label: "Value In Transit", value: "84,200 ر.س", sub: "5 vehicles", tone: "info" },
      { label: "This Week", value: "34 Transfers", sub: "5 branches", tone: "info" },
      { label: "Approval Pending", value: "3", sub: "Manager sign-off", tone: "warning" },
    ],
    // Transfers carry an ETA, not a created date — that's the column a date filter can act on.
    filters: ["Search", "From Branch", "To Branch", "Approver", "Status"],
    dateRangeFilters: ["ETA"],
    tableTitle: "Transfer Ledger",
    columns: [
      "Transfer #",
      "From",
      "To",
      "SKUs",
      "Qty",
      "Value (ر.س)",
      "Approver",
      "ETA",
      "Status",
    ],
    rows: [
      ["TR-2041", "WH-RUH-CW", "Jeddah", 22, 480, "38,400", "—", "03 Jul", "In Transit"],
      ["TR-2042", "WH-JED-CW", "Makkah", 8, 140, "12,200", "—", "02 Jul", "In Transit"],
      ["TR-2043", "Riyadh Main", "Dammam", 14, 210, "18,600", "—", "04 Jul", "Draft"],
      ["TR-2038", "WH-RUH-CW", "Madinah", 6, 90, "9,800", "Ahmed Al-Otaibi", "02 Jul", "Received"],
      ["TR-2035", "Jeddah", "Riyadh Main", 4, 42, "5,200", "—", "30 Jun", "Pending Approval"],
    ],
    statusCol: 8,
    actions: ["Create Transfer", "Export"],
    primaryAction: "Create Transfer",
  },
  {
    path: "/stock/bundles",
    group: "Stock",
    title: "Bundles & Systems",
    desc: "Package component SKUs into sellable kits with their own price and margin.",
    kpis: [
      { label: "Active Bundles", value: "2", sub: "2 total", tone: "success" },
      { label: "Avg Components", value: "2.0", sub: "Per bundle", tone: "info" },
      { label: "Avg Margin", value: "—", sub: "Bundle price vs cost", tone: "success" },
      { label: "Total Bundle Value", value: "700", sub: "Sum of bundle prices", tone: "info" },
    ],
    filters: ["Status", "Search"],
    tableTitle: "Bundle Catalog",
    columns: [
      "Code",
      "Bundle",
      "Components",
      "Component Cost (ر.س)",
      "Bundle Price (ر.س)",
      "Margin",
      "Status",
    ],
    rows: [
      ["BND-TILE-01", "Tiling Starter Kit", "2 SKUs", "364.00", "480.00", "24%", "Active"],
      ["BND-PLUMB-01", "Basic Plumbing Kit", "2 SKUs", "150.00", "220.00", "32%", "Active"],
    ],
    statusCol: 6,
    actions: ["Create Bundle", "Export"],
    primaryAction: "Create Bundle",
  },

  /* ========== FINANCE ========== */
  {
    path: "/finance/expenses",
    group: "Finance",
    title: "Expenses",
    desc: "Store/branch expenses, petty cash and operational cost records.",
    kpis: [
      { label: "Expenses MTD", value: "84,200 ر.س", sub: "5 branches", tone: "info" },
      { label: "Pending Approval", value: "12", sub: "18,400 ر.س", tone: "warning" },
      {
        label: "Petty Cash Balance",
        value: "6,800 ر.س",
        sub: "3 replenished today",
        tone: "success",
      },
      { label: "Top Category", value: "Logistics", sub: "24,100 ر.س", tone: "info" },
      { label: "This Week", value: "12,400 ر.س", sub: "-8% vs last", tone: "success" },
      { label: "Rejected", value: "3", sub: "Missing receipts", tone: "critical" },
      { label: "Reimbursements", value: "5", sub: "4,200 ر.س", tone: "warning" },
      { label: "Recurring", value: "18 rules", sub: "Utilities, rent", tone: "info" },
    ],
    filters: ["Search", "Branch", "Category", "Method", "Status"],
    dateRangeFilters: ["Date"],
    tableTitle: "Expense Ledger",
    columns: [
      "Expense #",
      "Date",
      "Branch",
      "Category",
      "Description",
      "Vendor",
      "Amount",
      "VAT",
      "Method",
      "Status",
    ],
    rows: [
      [
        "EXP-4021",
        "02 Jul 2026",
        "Riyadh Main",
        "Logistics",
        "Delivery truck fuel",
        "Petromin",
        "820 ر.س",
        "107 ر.س",
        "Petty Cash",
        "Approved",
      ],
      [
        "EXP-4022",
        "02 Jul 2026",
        "Jeddah",
        "Utilities",
        "Electricity July",
        "SEC",
        "3,800 ر.س",
        "495 ر.س",
        "Bank Transfer",
        "Pending",
      ],
      [
        "EXP-4023",
        "01 Jul 2026",
        "Riyadh Main",
        "Maintenance",
        "Cash drawer repair",
        "TechFix Co.",
        "480 ر.س",
        "62 ر.س",
        "Petty Cash",
        "Approved",
      ],
      [
        "EXP-4024",
        "01 Jul 2026",
        "Dammam",
        "Consumables",
        "Receipt rolls x50",
        "PaperMart",
        "220 ر.س",
        "28 ر.س",
        "Cash",
        "Approved",
      ],
      [
        "EXP-4025",
        "30 Jun 2026",
        "Makkah",
        "Marketing",
        "Local newspaper ad",
        "Al Riyadh",
        "1,500 ر.س",
        "195 ر.س",
        "Card",
        "Rejected",
      ],
    ],
    statusCol: 9,
    actions: ["Add Expense", "Approve", "Reject", "Export", "Reconcile"],
    primaryAction: "Add Expense",
  },
  {
    path: "/finance/purchase-orders",
    group: "Finance",
    title: "Purchase Orders",
    desc: "PO creation and status for suppliers and stock replenishment.",
    tabs: [
      "All",
      "Draft",
      "Pending Approval",
      "Sent",
      "In Transit",
      "Partial Receive",
      "Received",
      "Delayed",
      "Cancelled",
    ],
    kpis: [
      { label: "Open POs", value: "24", sub: "482,000 ر.س", tone: "info" },
      { label: "Awaiting Receipt", value: "9", sub: "3 delayed", tone: "warning" },
      { label: "Received This Week", value: "18", sub: "312,400 ر.س", tone: "success" },
      { label: "Delayed", value: "4", sub: ">7 days past ETA", tone: "critical" },
      { label: "Draft", value: "6", sub: "Needs approval", tone: "warning" },
      { label: "Auto-Reorder", value: "12 rules", sub: "Fired 3 today", tone: "info" },
      { label: "Avg Lead Time", value: "6.4 days", sub: "-0.5 vs last month", tone: "success" },
      { label: "Match Rate", value: "94%", sub: "PO ↔ Invoice", tone: "success" },
    ],
    // The PO ledger's only date column is the expected-delivery ETA — that's what a date range
    // here can narrow. (Ordered-date filtering lives on the Purchase Order Report, server-side.)
    filters: ["Search", "Supplier", "Branch(es)", "Status"],
    dateRangeFilters: ["ETA"],
    tableTitle: "Purchase Order Ledger",
    columns: ["PO #", "Supplier", "Branch", "ETA", "Lines", "PO Value", "Received %", "Status"],
    rows: [
      [
        "PO-558",
        "Yamama Cement Co.",
        "Riyadh Main Yard, Jeddah Industrial Branch",
        "02 Jul",
        4,
        "48,000 ر.س",
        "0%",
        "Sent",
      ],
      [
        "PO-559",
        "Saudi Ceramics Trading",
        "Jeddah Industrial Branch",
        "05 Jul",
        12,
        "84,200 ر.س",
        "40%",
        "PartialReceive",
      ],
      ["PO-560", "Hadeed Steel", "Riyadh Main Yard", "03 Jul", 6, "142,500 ر.س", "0%", "InTransit"],
      [
        "PO-561",
        "Gulf Building Supplies",
        "Riyadh Main Yard",
        "08 Jul",
        22,
        "38,600 ر.س",
        "0%",
        "Draft",
      ],
      ["PO-555", "Hadeed Steel", "Riyadh Main Yard", "29 Jun", 8, "22,400 ر.س", "100%", "Received"],
      [
        "PO-548",
        "Saudi Ceramics Trading",
        "Jeddah Industrial Branch",
        "25 Jun",
        5,
        "11,800 ر.س",
        "60%",
        "Delayed",
      ],
    ],
    statusCol: 7,
    actions: ["Create PO", "Submit", "Approve", "Dispatch", "Receive", "Cancel"],
    primaryAction: "Create PO",
  },
  {
    path: "/finance/pricing",
    group: "Finance",
    title: "Coupons, Discounts & Pricing",
    desc: "Price tiers, quantity discounts, trade pricing, coupons, restocking fees.",
    kpis: [
      { label: "Active Rules", value: "42", sub: "8 expiring soon", tone: "info" },
      { label: "Coupons Redeemed", value: "218", sub: "This month", tone: "success" },
      { label: "Discount Given", value: "18,400 ر.س", sub: "3.8% of net sales", tone: "warning" },
      { label: "Trade Pricing Tiers", value: "6", sub: "Contractor / Wholesale", tone: "info" },
      { label: "Bundle Sales", value: "84 Orders", sub: "42,100 ر.س", tone: "success" },
      { label: "Restocking Fees", value: "1,240 ر.س", sub: "This month", tone: "info" },
      { label: "Approval Pending", value: "3 rules", sub: "Manager review", tone: "warning" },
      { label: "Expired Rules", value: "12", sub: "Auto-archived", tone: "muted" },
    ],
    filters: ["Type", "Scope", "Status", "Branch"],
    tableTitle: "Pricing Rules",
    columns: [
      "Rule ID",
      "Name",
      "Type",
      "Scope",
      "Condition",
      "Action",
      "Priority",
      "Valid Until",
      "Status",
    ],
    rows: [
      [
        "PR-101",
        "Contractor Trade Price",
        "Trade Tier",
        "Contractor customers",
        "Any",
        "-12% list",
        10,
        "Ongoing",
        "Active",
      ],
      [
        "PR-102",
        "Cement Pallet Deal",
        "Quantity",
        "SKU: CEM-OPC-50KG",
        ">= 50 bags",
        "-8%",
        20,
        "31 Dec 2026",
        "Active",
      ],
      [
        "PR-103",
        "Ramadan Promo 2026",
        "Coupon",
        "All branches",
        "Code: RAM26",
        "5% off",
        30,
        "Expired 25 Apr",
        "Expired",
      ],
      [
        "PR-104",
        "Paint Bundle Waterproof",
        "Bundle",
        "Waterproofing kit",
        "Cart matches 80%",
        "150 ر.س off",
        15,
        "30 Sep 2026",
        "Active",
      ],
      [
        "PR-105",
        "Surplus Restocking Fee",
        "Fee",
        "Surplus returns",
        ">15 days",
        "+10% fee",
        5,
        "Ongoing",
        "Active",
      ],
      [
        "PR-106",
        "Loyalty 2x Points",
        "Promo",
        "Loyalty members",
        "Fridays",
        "2x points",
        25,
        "31 Jul 2026",
        "Pending Approval",
      ],
    ],
    statusCol: 8,
    actions: ["Create Pricing Rule", "Approve", "Test", "Activate", "Expire"],
    primaryAction: "Create Pricing Rule",
  },
  {
    path: "/finance/returns",
    group: "Finance",
    title: "Customer Returns",
    desc: "Standard returns, damaged returns, surplus returns, exchanges and refunds.",
    tabs: ["All", "Standard", "Damaged", "Surplus", "Exchange", "Pending Approval"],
    kpis: [
      { label: "Returns Today", value: "3,240 ر.س", sub: "12 tickets", tone: "warning" },
      { label: "Standard", value: "1,350 ر.س", sub: "6 tickets", tone: "info" },
      { label: "Damaged", value: "9 Items", sub: "920 ر.س", tone: "warning" },
      { label: "Surplus", value: "14 Items", sub: "970 ر.س", tone: "info" },
      { label: "VAT Reversal", value: "422 ر.س", sub: "ZATCA note issued", tone: "success" },
      { label: "Restocking Fees", value: "180 ر.س", sub: "3 tickets", tone: "info" },
      { label: "Pending Approval", value: "3", sub: "Damaged / High-value", tone: "warning" },
      { label: "Quarantine Added", value: "17 Items", sub: "QC review", tone: "warning" },
    ],
    filters: ["Search", "Branch", "Type", "Status", "Cashier", "Reason"],
    dateRangeFilters: ["Date"],
    tableTitle: "Return Ledger",
    columns: [
      "Return #",
      "Invoice",
      "Customer",
      "Type",
      "Product",
      "Refund",
      "Reason",
      "Approved By",
      "Status",
    ],
    rows: [
      [
        "RET-221",
        "INV-2026-00871",
        "Walk-in",
        "Standard",
        "PVC Pipe 2 Inch",
        "180 ر.س",
        "Wrong Size",
        "Fahad",
        "Completed",
      ],
      [
        "RET-222",
        "INV-2026-00872",
        "Al Noor Contracting",
        "Surplus",
        "OPC Cement 50KG",
        "750 ر.س",
        "Extra Material",
        "Ahmed",
        "Completed",
      ],
      [
        "RET-223",
        "INV-2026-00873",
        "Gulf Build Co.",
        "Damaged",
        "Grey Tile 60x60",
        "920 ر.س",
        "Broken Boxes",
        "Khalid",
        "Quarantine",
      ],
      [
        "RET-224",
        "INV-2026-00880",
        "Modern Villas Est.",
        "Damaged",
        "White Paint 20L",
        "430 ر.س",
        "Leakage",
        "—",
        "Pending Approval",
      ],
      [
        "RET-225",
        "INV-2026-00885",
        "Walk-in",
        "Exchange",
        "Electric Cable",
        "960 ر.س",
        "Wrong Specification",
        "Sara",
        "Completed",
      ],
    ],
    statusCol: 8,
    // Tabs mix return TYPES (Standard/Damaged/Surplus/Exchange, col 3) with a STATUS
    // (Pending Approval, col 8) — see mapReturns in src/lib/api/finance.ts for the live columns.
    tabFilterCols: [3, 8],
    actions: ["Process Return", "Approve", "Refund", "Quarantine", "DGRN", "Return Policy"],
    primaryAction: "New Return",
  },
  {
    path: "/finance/tax-zatca",
    group: "Finance",
    title: "Tax, Fees & ZATCA",
    desc: "VAT, fee configuration, fiscal invoice rules and ZATCA exception handling.",
    kpis: [
      { label: "VAT Collected MTD", value: "184,500 ر.س", sub: "15% standard", tone: "success" },
      { label: "VAT Reversed", value: "6,240 ر.س", sub: "Returns / credit notes", tone: "warning" },
      { label: "Net VAT Payable", value: "178,260 ر.س", sub: "Due 15 Aug", tone: "info" },
      { label: "Simplified Invoices", value: "8,412", sub: "Auto-cleared", tone: "success" },
      { label: "Full Tax Invoices", value: "684", sub: "B2B / >1,000 ر.س", tone: "info" },
      { label: "ZATCA Failures", value: "3", sub: "Retry queue", tone: "critical" },
      { label: "Zero-rated Items", value: "12 SKUs", sub: "Export sales", tone: "info" },
      { label: "Fee Rules", value: "6", sub: "Restock, delivery", tone: "info" },
    ],
    filters: ["Search", "Branch", "Type", "Status"],
    dateRangeFilters: ["Effective From"],
    tableTitle: "Tax & Fee Configuration",
    columns: [
      "Code",
      "Name",
      "Type",
      "Rate",
      "Applies To",
      "Effective From",
      "GL Account",
      "Status",
    ],
    rows: [
      [
        "TAX-STD",
        "Standard VAT 15%",
        "VAT",
        "15%",
        "All taxable SKUs",
        "01 Jul 2020",
        "24010",
        "Active",
      ],
      [
        "TAX-ZERO",
        "Zero-Rated Export",
        "VAT",
        "0%",
        "Export SKUs",
        "01 Jul 2020",
        "24012",
        "Active",
      ],
      ["TAX-EXEMPT", "Exempt Supplies", "VAT", "0%", "Selected SKUs", "01 Jan 2023", "—", "Active"],
      [
        "FEE-DELIV",
        "Delivery Fee",
        "Fee",
        "50 ر.س / order",
        "Delivery orders",
        "01 Jan 2024",
        "41220",
        "Active",
      ],
      [
        "FEE-RESTK",
        "Restocking Fee",
        "Fee",
        "10% of value",
        "Surplus returns >15d",
        "01 Jan 2024",
        "41240",
        "Active",
      ],
      [
        "ZTC-CSID",
        "ZATCA CSID (Riyadh)",
        "Compliance",
        "—",
        "Branch Riyadh Main",
        "12 May 2024",
        "—",
        "Valid",
      ],
    ],
    statusCol: 7,
    actions: ["Add Tax/Fee Code", "Export"],
    primaryAction: "Add Tax/Fee Code",
  },

  /* ========== SUPPLIERS ========== */
  {
    path: "/suppliers/suppliers",
    group: "Suppliers",
    title: "Suppliers",
    desc: "Supplier profiles, contacts, payment terms, lead time and purchase history.",
    kpis: [
      { label: "Active Suppliers", value: "84", sub: "6 categories", tone: "success" },
      { label: "On Hold", value: "3", sub: "Payment disputes", tone: "warning" },
      { label: "New This Month", value: "4", sub: "Onboarded", tone: "info" },
      { label: "Avg Fill Rate", value: "92%", sub: "-1% vs last month", tone: "warning" },
      { label: "Avg Lead Time", value: "6.4 days", sub: "Improving", tone: "success" },
      { label: "Outstanding Payable", value: "418,200 ر.س", sub: "12 suppliers", tone: "info" },
      { label: "Credit Notes", value: "18", sub: "This quarter", tone: "info" },
      { label: "Top Supplier", value: "Al Noor Cement", sub: "612K ر.س YTD", tone: "info" },
    ],
    filters: ["Category", "Status", "Payment Terms", "Search"],
    tableTitle: "Supplier Directory",
    columns: [
      "Code",
      "Supplier",
      "Category",
      "Contact",
      "VAT No.",
      "Terms",
      "Lead (days)",
      "Currency",
      "Status",
    ],
    rows: [
      [
        "SUP-001",
        "Yamama Cement Co.",
        "Cement",
        "+966114001100 — sales@yamama.example",
        "310000111111",
        "Net 30",
        5,
        "SAR",
        "Active",
      ],
      [
        "SUP-002",
        "Hadeed Steel",
        "Steel",
        "+966114002200 — sales@hadeed.example",
        "310000222222",
        "Net 45",
        10,
        "SAR",
        "Active",
      ],
      [
        "SUP-003",
        "Saudi Ceramics Trading",
        "Tiles",
        "+966114003300 — sales@saudiceramics.example",
        "310000333333",
        "Net 30",
        7,
        "SAR",
        "Active",
      ],
      [
        "SUP-004",
        "Gulf Building Supplies",
        "Plumbing, Electrical, Tools",
        "+966114004400 — sales@gulfbuild.example",
        "310000444444",
        "Net 15",
        3,
        "SAR",
        "Active",
      ],
    ],
    statusCol: 8,
    actions: ["Add Supplier", "Ledger", "Create PO"],
    primaryAction: "Add Supplier",
  },
  {
    path: "/suppliers/rts",
    group: "Suppliers",
    title: "Supplier Returns (RTS)",
    desc: "Return damaged/incorrect goods to supplier with credit note tracking.",
    kpis: [
      { label: "Open RTS", value: "6", sub: "48,200 ر.س", tone: "warning" },
      { label: "Awaiting Credit Note", value: "3", sub: "22,400 ر.س", tone: "warning" },
      { label: "Credit Received", value: "84,400 ر.س", sub: "MTD", tone: "success" },
      { label: "Damaged", value: "18 Items", sub: "6 SKUs", tone: "warning" },
      { label: "Incorrect", value: "9 Items", sub: "3 SKUs", tone: "info" },
      { label: "In Transit to Supplier", value: "2", sub: "Trucks scheduled", tone: "info" },
      { label: "Rejected by Supplier", value: "1", sub: "Escalated", tone: "critical" },
      { label: "Avg Cycle Time", value: "8.2 days", sub: "-1.4 days", tone: "success" },
    ],
    // "Date" belongs in dateRangeFilters, not filters: as a plain column filter it renders as an
    // exact-match multiselect over formatted day labels (and, since the column used to be called
    // "Created", resolved to nothing at all and rendered as an inert chip). As a range filter it
    // gets the shared presets + custom range and actually narrows the ledger.
    filters: ["Search", "Supplier", "Branch", "Warehouse", "Reason", "Status"],
    dateRangeFilters: ["Date"],
    tableTitle: "RTS Ledger",
    columns: [
      "RTS #",
      "Supplier",
      "Branch",
      "Warehouse",
      "Linked PO",
      "Reason",
      "Items",
      "Value (ر.س)",
      "Credit Note",
      "Date",
      "Status",
    ],
    rows: [
      [
        "RTS-341",
        "Gulf Building Supplies",
        "Riyadh Main Yard",
        "PO-561",
        "Damaged in transit",
        12,
        "9,240",
        "—",
        "01 Jul",
        "AwaitingCredit",
      ],
      [
        "RTS-342",
        "Saudi Ceramics Trading",
        "Jeddah Industrial Branch",
        "PO-559",
        "Wrong shade",
        8,
        "3,520",
        "CN-88",
        "30 Jun",
        "CreditReceived",
      ],
      [
        "RTS-343",
        "Hadeed Steel",
        "Riyadh Main Yard",
        "PO-560",
        "Diameter mismatch",
        4,
        "7,800",
        "—",
        "29 Jun",
        "Dispatched",
      ],
      [
        "RTS-344",
        "Yamama Cement Co.",
        "Riyadh Main Yard",
        "PO-558",
        "Broken bags",
        22,
        "480",
        "CN-91",
        "28 Jun",
        "CreditReceived",
      ],
      [
        "RTS-345",
        "Gulf Building Supplies",
        "Jeddah Industrial Branch",
        "PO-548",
        "Missing fittings",
        3,
        "620",
        "—",
        "27 Jun",
        "Rejected",
      ],
    ],
    statusCol: 9,
    actions: ["Create RTS", "Dispatch", "Record Credit Note", "Reject"],
    primaryAction: "Create RTS",
  },

  /* ========== NETWORK ========== */
  {
    path: "/network/branches",
    group: "Network",
    title: "Branches",
    desc: "Branch master, addresses, business hours, tax settings and operational status.",
    kpis: [
      { label: "Active Branches", value: "5", sub: "5/5 branches", tone: "success" },
      { label: "Total Orders", value: "1,240", sub: "All branches", tone: "info" },
      { label: "Total Terminals", value: "21", sub: "Registered", tone: "info" },
    ],
    filters: ["Search"],
    layout: "cards",
    cardConfig: {
      titleCol: 1,
      subtitleCol: 2,
      statCols: [
        { label: "Terminals", col: 5 },
        { label: "Orders", col: 6 },
      ],
    },
    tableTitle: "Branch Master",
    columns: [
      "Code",
      "Branch",
      "City",
      "Business Hours",
      "VAT No.",
      "Terminals",
      "Orders",
      "Status",
    ],
    rows: [
      ["BR-01", "Riyadh Main", "Riyadh", "07:00 - 23:00", "310000000001", 6, 412, "Active"],
      ["BR-02", "Jeddah Branch", "Jeddah", "08:00 - 22:00", "310000000002", 5, 298, "Active"],
      ["BR-03", "Dammam Branch", "Dammam", "08:00 - 22:00", "310000000003", 4, 231, "Active"],
      ["BR-04", "Makkah Branch", "Makkah", "06:00 - 24:00", "310000000004", 3, 172, "Active"],
      ["BR-05", "Madinah Branch", "Madinah", "06:00 - 24:00", "310000000005", 3, 127, "Active"],
    ],
    statusCol: 7,
    actions: ["Add Branch", "Configure", "Activate", "Deactivate"],
    primaryAction: "Add Branch",
  },
  {
    path: "/network/terminals",
    group: "Network",
    title: "Terminals",
    desc: "Register/terminal mapping, cashier assignment and sync state.",
    kpis: [
      { label: "Total Terminals", value: "6", sub: "3 branches", tone: "info" },
      { label: "Online", value: "4", sub: "67% uptime", tone: "success" },
      { label: "Offline", value: "1", sub: "Needs attention", tone: "critical" },
      { label: "Idle", value: "1", sub: "No activity", tone: "warning" },
    ],
    filters: ["Branch", "Status", "Search"],
    dateRangeFilters: ["Sync Date"],
    tableTitle: "Terminal Fleet",
    columns: ["Terminal", "Branch", "Cashier", "IP / MAC", "Last Sync", "Status"],
    rows: [
      ["POS-01", "Riyadh Main", "Ahmed Al-Harbi", "10.1.10.11", "Just now", "Online"],
      ["POS-02", "Riyadh Main", "Fahad Al-Qahtani", "10.1.10.12", "Just now", "Online"],
      ["POS-03", "Riyadh Main", "Sara Al-Otaibi", "10.1.10.13", "45 min ago", "Offline"],
      ["POS-04", "Riyadh Main", "Khalid Al-Mutairi", "10.1.10.14", "1 min ago", "Online"],
      ["POS-05", "Jeddah", "Noura Al-Salem", "10.2.10.11", "2 min ago", "Idle"],
      ["POS-06", "Dammam", "Abdullah Al-Rashid", "10.3.10.11", "Just now", "Online"],
    ],
    statusCol: 5,
    actions: ["Add Terminal", "Assign Cashier", "Monitor", "Force Sync"],
    primaryAction: "Add Terminal",
  },
  {
    path: "/network/devices",
    group: "Network",
    title: "Devices",
    desc: "Barcode scanner, receipt printer, cash drawer, card terminal, label printer, scale, customer display.",
    kpis: [
      { label: "Total Devices", value: "6", sub: "3 terminals", tone: "info" },
      { label: "Healthy", value: "4", sub: "67%", tone: "success" },
      { label: "Needs Attention", value: "1", sub: "Maintenance ticket", tone: "warning" },
      { label: "Network OK", value: "4/6", sub: "Synced", tone: "warning" },
    ],
    filters: ["Branch", "Status", "Search"],
    tableTitle: "Device Registry",
    columns: ["Device ID", "Type", "Terminal", "Branch", "Model", "Sync", "Last Test", "Status"],
    rows: [
      [
        "DEV-1101",
        "Receipt Printer",
        "POS-01",
        "Riyadh Main",
        "Epson TM-T88VI",
        "Synced",
        "02 Jul",
        "Healthy",
      ],
      [
        "DEV-1102",
        "Barcode Scanner",
        "POS-01",
        "Riyadh Main",
        "Zebra DS2208",
        "Synced",
        "02 Jul",
        "Healthy",
      ],
      [
        "DEV-1103",
        "Cash Drawer",
        "POS-01",
        "Riyadh Main",
        "APG Vasario",
        "Synced",
        "01 Jul",
        "Healthy",
      ],
      [
        "DEV-1104",
        "Card Reader (Mada)",
        "POS-01",
        "Riyadh Main",
        "Ingenico Move/5000",
        "Synced",
        "02 Jul",
        "Healthy",
      ],
      [
        "DEV-1130",
        "Receipt Printer",
        "POS-03",
        "Riyadh Main",
        "Epson TM-T88VI",
        "Failed",
        "01 Jul",
        "Disconnected",
      ],
      [
        "DEV-1140",
        "Label Printer",
        "POS-04",
        "Riyadh Main",
        "Zebra ZD421",
        "Pending",
        "30 Jun",
        "Faulty",
      ],
    ],
    statusCol: 7,
    actions: ["Pair Device", "Test Print", "Open Drawer", "Troubleshoot"],
    primaryAction: "Pair Device",
  },

  /* ========== INSIGHTS ========== */
  {
    path: "/insights/sales",
    group: "Insights",
    title: "Sales Analytics",
    desc: "Sales by branch, category, product, cashier, terminal and customer type.",
    kpis: [
      { label: "Net Sales MTD", value: "1,284,500 ر.س", sub: "+12% vs prior", tone: "success" },
      { label: "Gross Margin", value: "22.5%", sub: "Target 22%", tone: "success" },
      { label: "Top Category", value: "Cement & Aggregates", sub: "284K ر.س", tone: "info" },
      { label: "Top Branch", value: "Riyadh Main", sub: "34% share", tone: "info" },
      { label: "Top Cashier", value: "Ahmed Al-Harbi", sub: "12,400 ر.س today", tone: "info" },
      { label: "Contractor Share", value: "48%", sub: "612K ر.س", tone: "info" },
      { label: "Basket Size", value: "171 ر.س", sub: "B2B: 1,240 ر.س", tone: "info" },
      { label: "Discount Ratio", value: "3.8%", sub: "Within target", tone: "success" },
    ],
    // This page is a pre-aggregated segment breakdown — the only real cut is the segment itself.
    // Period/branch/category slicing lives on Insights → Reports, which filters server-side.
    filters: ["Search", "Segment"],
    tableTitle: "Sales by Segment",
    columns: [
      "Segment",
      "Value (ر.س)",
      "Share %",
      "Tx",
      "Avg Basket",
      "Returns %",
      "Margin %",
      "Trend",
    ],
    rows: [
      ["Cement & Aggregates", "284,000", "22%", 1240, "229 ر.س", "1.5%", "18%", "▲"],
      ["Steel & Rebar", "218,400", "17%", 384, "568 ر.س", "0.8%", "14%", "▲"],
      ["Tiles & Flooring", "184,200", "14%", 942, "195 ر.س", "3.2%", "26%", "▲"],
      ["Paint & Chemicals", "128,600", "10%", 812, "158 ر.س", "2.1%", "31%", "▬"],
      ["Plumbing", "84,100", "6%", 1420, "59 ر.س", "1.0%", "28%", "▲"],
      ["Electrical", "72,300", "5%", 1210, "60 ر.س", "0.5%", "30%", "▲"],
      ["Hardware & Tools", "58,900", "5%", 940, "63 ر.س", "1.8%", "34%", "▬"],
      ["Glass & Aluminum", "42,000", "3%", 210, "200 ر.س", "0.0%", "24%", "▲"],
    ],
    actions: ["Drill Down", "Export", "Save View"],
  },
  {
    path: "/insights/reports",
    group: "Insights",
    title: "Reports",
    desc: "Operational, financial, inventory, returns, VAT/ZATCA and performance reports.",
    kpis: [
      { label: "Reports Available", value: "42", sub: "12 favorited", tone: "info" },
      { label: "Scheduled", value: "18", sub: "Daily / Weekly / Monthly", tone: "info" },
      { label: "Downloads Today", value: "62", sub: "24 users", tone: "success" },
      { label: "Failed Exports", value: "1", sub: "Retry available", tone: "warning" },
      { label: "Saved Views", value: "84", sub: "12 shared", tone: "info" },
      { label: "Last Refresh", value: "2 min ago", sub: "Auto every 15 min", tone: "success" },
      { label: "Data Latency", value: "< 30s", sub: "Healthy", tone: "success" },
      { label: "Restricted Reports", value: "6", sub: "Margin-protected", tone: "warning" },
    ],
    filters: ["Category", "Owner", "Frequency", "Search"],
    tableTitle: "Report Catalog",
    columns: [
      "Code",
      "Report",
      "Category",
      "Owner",
      "Last Run",
      "Rows",
      "Frequency",
      "Format",
      "Status",
    ],
    rows: [
      [
        "RPT-01",
        "Daily Sales by Hour",
        "Sales",
        "Store Manager",
        "02:45 PM",
        12,
        "Every 15 min",
        "PDF/XLSX",
        "Ready",
      ],
      [
        "RPT-02",
        "Cashier Sales",
        "Sales",
        "Store Manager",
        "02:45 PM",
        6,
        "Daily",
        "PDF/XLSX",
        "Ready",
      ],
      [
        "RPT-05",
        "Low Stock Report",
        "Inventory",
        "Inventory Mgr",
        "02:30 PM",
        34,
        "Every 30 min",
        "XLSX",
        "Ready",
      ],
      [
        "RPT-06",
        "Returns Report",
        "Returns",
        "Finance Mgr",
        "02:15 PM",
        12,
        "Daily",
        "PDF/XLSX",
        "Ready",
      ],
      [
        "RPT-08",
        "VAT / ZATCA Report",
        "Compliance",
        "Finance Mgr",
        "12:00 PM",
        8412,
        "Daily",
        "XLSX",
        "Ready",
      ],
      [
        "RPT-09",
        "Stock Transfer Report",
        "Inventory",
        "Inventory Mgr",
        "01:00 PM",
        34,
        "Daily",
        "XLSX",
        "Ready",
      ],
      [
        "RPT-11",
        "Profit Margin Report",
        "Finance",
        "Finance Mgr",
        "12:00 PM",
        6412,
        "Weekly",
        "XLSX",
        "Restricted",
      ],
      ["RPT-12", "Audit Trail", "Admin", "Auditor", "12:00 PM", 682, "Weekly", "CSV", "Ready"],
    ],
    statusCol: 8,
    actions: ["Open", "Download", "Schedule", "Save View"],
  },
  {
    path: "/insights/kpi",
    group: "Insights",
    title: "KPI Evaluation",
    desc: "Target vs actual, cashier productivity, branch ranking, stock and service KPIs.",
    kpis: [
      { label: "KPIs Tracked", value: "24", sub: "6 categories", tone: "info" },
      { label: "On Target", value: "17", sub: "71%", tone: "success" },
      { label: "Below Target", value: "5", sub: "Action needed", tone: "warning" },
      { label: "Critical", value: "2", sub: "Escalation", tone: "critical" },
      { label: "Best Branch", value: "Riyadh Main", sub: "112% of target", tone: "success" },
      { label: "Lowest Branch", value: "Madinah", sub: "82% of target", tone: "warning" },
      { label: "Top Cashier", value: "Ahmed Al-Harbi", sub: "128% productivity", tone: "success" },
      { label: "Review Cycle", value: "Monthly", sub: "Next: 05 Aug", tone: "info" },
    ],
    filters: ["Search", "Category", "Owner", "Period", "Status"],
    tableTitle: "KPI Scorecard",
    columns: ["KPI", "Category", "Owner", "Target", "Actual", "Variance", "Status", "Period"],
    rows: [
      [
        "Net Sales",
        "Sales",
        "Store Manager",
        "1,200,000 ر.س",
        "1,284,500 ر.س",
        "+7%",
        "On Target",
        "MTD",
      ],
      ["Gross Margin", "Finance", "Finance Mgr", "22%", "22.5%", "+0.5pp", "On Target", "MTD"],
      ["Return Rate", "Returns", "Store Manager", "≤ 3%", "2.4%", "-0.6pp", "On Target", "MTD"],
      [
        "Cash Variance",
        "Cashier",
        "Store Manager",
        "≤ 50 ر.س",
        "50 ر.س",
        "0",
        "Below Target",
        "Today",
      ],
      [
        "Stock-out %",
        "Inventory",
        "Inventory Mgr",
        "≤ 1%",
        "1.4%",
        "+0.4pp",
        "Below Target",
        "Week",
      ],
      [
        "ZATCA Success",
        "Compliance",
        "Finance Mgr",
        "≥ 99.5%",
        "99.6%",
        "+0.1pp",
        "On Target",
        "MTD",
      ],
      ["Terminal Uptime", "Network", "IT", "≥ 99%", "97.8%", "-1.2pp", "Critical", "Today"],
      ["Delivery SLA", "Delivery", "Dispatch", "≥ 95%", "89%", "-6pp", "Critical", "Week"],
    ],
    statusCol: 6,
    actions: ["Edit Target", "View Trend", "Export"],
  },
  {
    path: "/insights/bi",
    group: "Insights",
    title: "Business Intelligence",
    desc: "BI dashboards and data feed status for advanced analytics.",
    kpis: [
      { label: "Data Feeds", value: "12", sub: "10 healthy", tone: "success" },
      { label: "Last Extract", value: "18 min ago", sub: "Every 30 min", tone: "success" },
      { label: "Failed Rows", value: "42", sub: "Retry queued", tone: "warning" },
      { label: "Warehouse Size", value: "184 GB", sub: "+2.4 GB / day", tone: "info" },
      { label: "Dashboards Published", value: "24", sub: "6 pinned", tone: "info" },
      { label: "Active Consumers", value: "38", sub: "Finance, Ops, IT", tone: "info" },
      { label: "Data Quality Score", value: "96%", sub: "Healthy", tone: "success" },
      { label: "Sensitive Masking", value: "On", sub: "PII / Margin", tone: "success" },
    ],
    filters: ["Search", "Feed", "Source", "Frequency", "Status"],
    dateRangeFilters: ["Last Run"],
    tableTitle: "Data Feed Health",
    columns: [
      "Feed",
      "Source",
      "Destination",
      "Frequency",
      "Last Run",
      "Rows",
      "Failed",
      "Latency",
      "Status",
    ],
    rows: [
      [
        "Sales Feed",
        "POS Transactions",
        "BI Warehouse",
        "Every 30 min",
        "02:30 PM",
        8412,
        0,
        "12s",
        "Healthy",
      ],
      [
        "Inventory Feed",
        "Stocks",
        "BI Warehouse",
        "Every 30 min",
        "02:30 PM",
        6412,
        0,
        "18s",
        "Healthy",
      ],
      [
        "ZATCA Feed",
        "Invoices",
        "Compliance DW",
        "Every 15 min",
        "02:45 PM",
        8412,
        3,
        "8s",
        "Healthy",
      ],
      ["Cashier Feed", "Shift Ledger", "HR / BI", "Hourly", "02:00 PM", 41, 0, "3s", "Healthy"],
      [
        "Supplier Feed",
        "PO + RTS",
        "Finance DW",
        "Every 6h",
        "12:00 PM",
        128,
        42,
        "22s",
        "Degraded",
      ],
      ["Delivery Feed", "Dispatch", "Ops DW", "Every 15 min", "02:45 PM", 34, 0, "6s", "Healthy"],
    ],
    statusCol: 8,
    actions: ["Refresh", "Retry Failed", "View Schema", "Export"],
  },

  /* ========== ADMIN ========== */
  {
    path: "/admin/overview",
    group: "Admin",
    title: "Admin Overview",
    desc: "System health, tenants, plans, modules, permissions and alerts.",
    kpis: [
      { label: "System Health", value: "Healthy", sub: "All services green", tone: "success" },
      { label: "Active Users", value: "42", sub: "6 admins", tone: "info" },
      { label: "Pending Approvals", value: "8", sub: "Discount / Refund", tone: "warning" },
      { label: "Failed Integrations", value: "1", sub: "ERP journal push", tone: "critical" },
      { label: "Open Maintenance", value: "6 tickets", sub: "2 critical", tone: "warning" },
      { label: "Critical Audit Events", value: "4", sub: "Last 24h", tone: "warning" },
      { label: "Compliance Tasks", value: "3 due", sub: "This week", tone: "warning" },
      { label: "License Usage", value: "26 / 30", sub: "Terminals", tone: "success" },
    ],
    filters: ["Search", "Area", "Owner", "Status"],
    tableTitle: "Health Overview",
    columns: ["Area", "Status", "Since", "Owner", "Metric", "Value", "SLA", "Next Action"],
    rows: [
      ["Data API", "Healthy", "24 days", "IT", "Availability", "99.98%", "≥ 99.9%", "Monitor"],
      [
        "ZATCA Integration",
        "Degraded",
        "2 hr",
        "Finance",
        "Success Rate",
        "97.8%",
        "≥ 99.5%",
        "Retry Batch",
      ],
      ["Payment Gateway", "Healthy", "18 days", "Finance", "Latency", "620 ms", "≤ 1s", "Monitor"],
      [
        "ERP Journal Push",
        "Failed",
        "35 min",
        "Finance",
        "Last Batch",
        "12 errors",
        "0 errors",
        "Investigate",
      ],
      ["Backups", "Healthy", "1 day", "IT", "Last Backup", "03:00 AM", "Daily", "Monitor"],
    ],
    statusCol: 1,
    actions: ["Investigate", "Assign", "Escalate"],
  },
  {
    path: "/admin/categories",
    group: "Admin",
    title: "Categories",
    desc: "Building material category tree.",
    kpis: [
      { label: "Categories", value: "14", sub: "3 levels deep", tone: "info" },
      { label: "Subcategories", value: "82", sub: "Mapped to SKUs", tone: "info" },
      { label: "SKUs Assigned", value: "6,412", sub: "100% mapped", tone: "success" },
      { label: "Empty Categories", value: "0", sub: "Healthy", tone: "success" },
      { label: "Non-Returnable", value: "3", sub: "Paint, Chem, Custom Glass", tone: "warning" },
      { label: "Recently Edited", value: "6", sub: "Last 7 days", tone: "info" },
    ],
    filters: ["Search", "Parent", "Status"],
    tableTitle: "Category Tree",
    columns: ["Code", "Category", "SKUs", "Status"],
    rows: [
      ["CAT-01", "Cement", 42, "Active"],
      ["CAT-02", "Aggregates", 28, "Active"],
      ["CAT-03", "Steel & Rebar", 84, "Active"],
      ["CAT-04", "Tiles & Flooring", 612, "Active"],
      ["CAT-05", "Paint & Chemicals", 384, "Active"],
      ["CAT-06", "Plumbing", 940, "Active"],
      ["CAT-06a", "↳ Pipes", 420, "Active"],
      ["CAT-07", "Electrical", 820, "Active"],
      ["CAT-07a", "↳ Switches", 260, "Active"],
      ["CAT-07b", "↳ Wire", 340, "Active"],
      ["CAT-08", "Glass & Aluminum", 128, "Active"],
    ],
    statusCol: 3,
    actions: ["Create Category", "Export"],
    primaryAction: "Create Category",
  },
  {
    path: "/admin/rules",
    group: "Admin",
    title: "Rules Engine",
    desc: "Business rules for pricing, returns, approvals, credit, stock blocking and offline limits.",
    kpis: [
      { label: "Total Rules", value: "84", sub: "12 categories", tone: "info" },
      { label: "Active", value: "72", sub: "Applied at POS", tone: "success" },
      { label: "Inactive", value: "12", sub: "Not applied at POS", tone: "muted" },
      { label: "Rule Overrides Today", value: "18", sub: "6 by supervisor", tone: "info" },
      { label: "Failed Tests", value: "2", sub: "Fix before activate", tone: "critical" },
      { label: "Last Change", value: "12 min ago", sub: "By admin_ali", tone: "info" },
    ],
    filters: ["Search", "Module", "Trigger", "Approver", "Status"],
    tableTitle: "Rules Catalog",
    columns: [
      "Rule ID",
      "Module",
      "Type",
      "Scope",
      "Condition",
      "Action",
      "Priority",
      "Effective From",
      "Status",
    ],
    rows: [
      [
        "RUL-201",
        "Returns",
        "Return Window",
        "Surplus",
        ">15 days",
        "Block + 10% fee",
        10,
        "01 Jan 2024",
        "Active",
      ],
      [
        "RUL-202",
        "Pricing",
        "Discount Cap",
        "All cashiers",
        ">10% discount",
        "Require supervisor",
        20,
        "01 Jan 2024",
        "Active",
      ],
      [
        "RUL-203",
        "Credit",
        "Credit Limit",
        "Contractor",
        "Balance > limit",
        "Block new sale",
        30,
        "01 Jan 2024",
        "Active",
      ],
      [
        "RUL-204",
        "Stock",
        "Reservation",
        "Delivery orders",
        ">1,000 ر.س",
        "Auto-reserve 24h",
        15,
        "01 Mar 2024",
        "Active",
      ],
      [
        "RUL-205",
        "Offline",
        "Offline Limit",
        "All terminals",
        ">500 tx queued",
        "Block new sale",
        5,
        "01 Jan 2024",
        "Active",
      ],
      [
        "RUL-206",
        "Approvals",
        "Refund",
        "All branches",
        ">500 ر.س cash refund",
        "Manager approval",
        25,
        "01 Jan 2024",
        "Active",
      ],
    ],
    statusCol: 8,
    actions: ["Create Rule", "Test", "Activate", "Deactivate", "Audit"],
    primaryAction: "Create Rule",
  },
  {
    path: "/admin/users",
    group: "Admin",
    title: "Registered Users",
    desc: "Employees/users, PIN reset, biometric flag, branch assignment and status.",
    kpis: [
      { label: "Total Users", value: "42", sub: "6 roles", tone: "info" },
      { label: "Active", value: "38", sub: "90%", tone: "success" },
      { label: "Inactive", value: "4", sub: "Suspended / left", tone: "muted" },
      { label: "Biometric Enabled", value: "26", sub: "62% coverage", tone: "info" },
      { label: "PIN Reset (30d)", value: "12", sub: "6 admin-initiated", tone: "info" },
      { label: "Failed Login (24h)", value: "3", sub: "1 locked", tone: "warning" },
      { label: "MFA Enabled", value: "18", sub: "All admins", tone: "success" },
      { label: "Pending Onboarding", value: "2", sub: "New hires", tone: "info" },
    ],
    filters: ["Role", "Branch", "Status", "Search"],
    tableTitle: "User Directory",
    columns: [
      "Employee ID",
      "Name",
      "Role",
      "Branch",
      "Email",
      "PIN",
      "Biometric",
      "Last Login",
      "Status",
    ],
    rows: [
      [
        "EMP-001",
        "Ahmed Al-Harbi",
        "Store Manager",
        "Riyadh Main",
        "ahmed@mimony.sa",
        "Set",
        "Yes",
        "02 Jul 08:00",
        "Active",
      ],
      [
        "EMP-002",
        "Fahad Al-Qahtani",
        "Cashier",
        "Riyadh Main",
        "fahad@mimony.sa",
        "Set",
        "Yes",
        "02 Jul 09:00",
        "Active",
      ],
      [
        "EMP-003",
        "Sara Al-Otaibi",
        "Cashier",
        "Riyadh Main",
        "sara@mimony.sa",
        "Set",
        "No",
        "02 Jul 08:30",
        "Active",
      ],
      [
        "EMP-004",
        "Khalid Al-Mutairi",
        "Cashier",
        "Riyadh Main",
        "khalid@mimony.sa",
        "Set",
        "Yes",
        "02 Jul 10:00",
        "Active",
      ],
      [
        "EMP-005",
        "Noura Al-Salem",
        "Supervisor",
        "Jeddah",
        "noura@mimony.sa",
        "Set",
        "Yes",
        "02 Jul 11:00",
        "Active",
      ],
      [
        "EMP-018",
        "Abdulrahman Al-Fahad",
        "Auditor",
        "HQ",
        "abdulrahman@mimony.sa",
        "Set",
        "No",
        "01 Jul 16:30",
        "Active",
      ],
      [
        "EMP-022",
        "Suspended Cashier",
        "Cashier",
        "Dammam",
        "—",
        "Reset",
        "No",
        "12 Jun",
        "Suspended",
      ],
    ],
    statusCol: 8,
    actions: ["Add User", "Reset PIN", "Reset Password", "Disable", "Assign Branch"],
    primaryAction: "Add User",
  },
  {
    path: "/admin/maintenance",
    group: "Admin",
    title: "Maintenance",
    desc: "Device, product and operational maintenance tickets.",
    tabs: ["All", "Open", "In Progress", "Resolved", "Closed"],
    kpis: [
      { label: "Open Tickets", value: "6", sub: "2 critical", tone: "warning" },
      { label: "In Progress", value: "4", sub: "IT + Vendor", tone: "info" },
      { label: "Resolved (7d)", value: "12", sub: "Avg 6h", tone: "success" },
      { label: "Critical", value: "1", sub: "Terminal down", tone: "critical" },
      { label: "SLA Breach", value: "1", sub: "> 24h open", tone: "critical" },
      { label: "Vendor Assigned", value: "3", sub: "External SLA", tone: "info" },
      { label: "Recurring", value: "2 items", sub: "POS-04 drawer", tone: "warning" },
      { label: "MTTR", value: "5.8 hr", sub: "-1.2 vs prior week", tone: "success" },
    ],
    filters: ["Branch", "Severity", "Owner", "Status"],
    tableTitle: "Maintenance Tickets",
    columns: [
      "Ticket #",
      "Device / Module",
      "Branch",
      "Severity",
      "Owner",
      "Created",
      "SLA",
      "Age",
      "Status",
    ],
    rows: [
      [
        "MNT-441",
        "POS-03 Terminal",
        "Riyadh Main",
        "Critical",
        "IT Support",
        "02 Jul 02:00 PM",
        "4h",
        "45 min",
        "In Progress",
      ],
      [
        "MNT-440",
        "Cash Drawer POS-04",
        "Riyadh Main",
        "Warning",
        "TechFix Vendor",
        "01 Jul 04:00 PM",
        "24h",
        "22h",
        "In Progress",
      ],
      [
        "MNT-438",
        "Label Printer POS-04",
        "Riyadh Main",
        "Warning",
        "IT Support",
        "30 Jun",
        "48h",
        "2d",
        "Open",
      ],
      [
        "MNT-436",
        "Card Terminal POS-05",
        "Jeddah",
        "Warning",
        "Payment Vendor",
        "29 Jun",
        "12h",
        "3d",
        "Resolved",
      ],
      [
        "MNT-434",
        "Barcode Scanner POS-02",
        "Riyadh Main",
        "Info",
        "IT Support",
        "28 Jun",
        "72h",
        "4d",
        "Closed",
      ],
    ],
    statusCol: 8,
    actions: ["Create Ticket", "Assign", "Update", "Close"],
    primaryAction: "Create Ticket",
  },
  {
    path: "/admin/zatca-invoices",
    group: "Admin",
    title: "ZATCA Invoices",
    desc: "Invoice submission logs, QR status, clearance status and failed invoice queue.",
    kpis: [
      { label: "Submitted Today", value: "286", sub: "100% queued", tone: "success" },
      { label: "Cleared", value: "283", sub: "99.0%", tone: "success" },
      { label: "Queued Offline", value: "1", sub: "Will sync", tone: "warning" },
      { label: "Failed", value: "3", sub: "Retry available", tone: "critical" },
      { label: "Full Tax Invoices", value: "42", sub: "B2B / High value", tone: "info" },
      { label: "Simplified", value: "244", sub: "Retail", tone: "info" },
      { label: "Avg Clearance Time", value: "1.8s", sub: "Healthy", tone: "success" },
      { label: "CSID Valid Until", value: "12 May 2027", sub: "Auto-renew on", tone: "success" },
    ],
    filters: ["Search", "Type", "Status"],
    dateRangeFilters: ["Submitted"],
    tableTitle: "Invoice Submission Log",
    columns: [
      "Invoice",
      "Order",
      "Type",
      "Amount",
      "VAT",
      "QR",
      "Hash / UUID",
      "Submitted",
      "Status",
    ],
    rows: [
      [
        "INV-2026-00888",
        "ORD-8088",
        "Simplified",
        "1,250 ر.س",
        "163 ر.س",
        "OK",
        "9f8a…c221",
        "02:12 PM",
        "Cleared",
      ],
      [
        "INV-2026-00889",
        "ORD-8089",
        "Full",
        "7,850 ر.س",
        "1,024 ر.س",
        "OK",
        "8d1b…44f0",
        "02:18 PM",
        "Cleared",
      ],
      [
        "INV-2026-00890",
        "ORD-8090",
        "Simplified",
        "430 ر.س",
        "56 ر.س",
        "Pending",
        "—",
        "02:28 PM",
        "Queued Offline",
      ],
      [
        "INV-2026-00891",
        "ORD-8091",
        "Full",
        "11,500 ر.س",
        "1,500 ر.س",
        "Fail",
        "—",
        "02:41 PM",
        "Failed",
      ],
      [
        "INV-2026-00892",
        "ORD-8092",
        "Simplified",
        "2,300 ر.س",
        "300 ر.س",
        "OK",
        "3c22…9bd4",
        "02:38 PM",
        "Submitted",
      ],
    ],
    statusCol: 8,
    actions: ["Retry", "View Error", "Export"],
  },
  {
    path: "/admin/zatca-settings",
    group: "Admin",
    title: "ZATCA Phase 2 Settings",
    desc: "Taxpayer credentials, CSID, invoice numbering and clearance configuration.",
    kpis: [
      { label: "Branches Onboarded", value: "5", sub: "One CSID per branch", tone: "success" },
      { label: "Production Ready", value: "5", sub: "100%", tone: "success" },
      { label: "Invoices Issued", value: "1,245", sub: "Total ICV count", tone: "info" },
      { label: "Clearance Success", value: "99.6%", sub: "MTD", tone: "success" },
      { label: "Retry Rules", value: "3", sub: "Exponential backoff", tone: "info" },
      { label: "Sandbox Mode", value: "Off", sub: "Production live", tone: "warning" },
    ],
    filters: ["Branch", "Environment", "Status"],
    tableTitle: "Fiscal Integration Configuration",
    columns: [
      "Branch",
      "VAT No.",
      "CSID Status",
      "Environment",
      "Numbering",
      "Last Test",
      "Next Renewal",
      "Status",
    ],
    rows: [
      [
        "Riyadh Main",
        "310000000001",
        "Valid",
        "Production",
        "INV-2026-#####",
        "02 Jul 02:44 PM",
        "12 May 2027",
        "Healthy",
      ],
      [
        "Jeddah",
        "310000000002",
        "Valid",
        "Production",
        "JED-2026-#####",
        "02 Jul 02:44 PM",
        "18 May 2027",
        "Healthy",
      ],
      [
        "Dammam",
        "310000000003",
        "Valid",
        "Production",
        "DMM-2026-#####",
        "02 Jul 02:44 PM",
        "22 May 2027",
        "Healthy",
      ],
      [
        "Makkah",
        "310000000004",
        "Valid",
        "Production",
        "MAK-2026-#####",
        "02 Jul 02:44 PM",
        "05 Jun 2027",
        "Healthy",
      ],
      [
        "Madinah",
        "310000000005",
        "Valid",
        "Production",
        "MED-2026-#####",
        "02 Jul 02:44 PM",
        "10 Jun 2027",
        "Healthy",
      ],
    ],
    statusCol: 7,
    actions: ["Test Connection", "Rotate Certificate", "Configure"],
  },
  {
    path: "/admin/compliance",
    group: "Admin",
    title: "Compliance",
    desc: "Audit/compliance controls, data retention, access review and exception reports.",
    kpis: [
      { label: "Compliance Score", value: "94%", sub: "Target ≥ 90%", tone: "success" },
      { label: "Open Tasks", value: "3", sub: "Due this week", tone: "warning" },
      { label: "Overdue", value: "1", sub: "Access review Q2", tone: "critical" },
      { label: "Data Retention", value: "7 years", sub: "ZATCA policy", tone: "success" },
      { label: "Access Reviews", value: "4 / year", sub: "Next: 30 Sep", tone: "info" },
      { label: "Exceptions Logged", value: "18", sub: "MTD", tone: "info" },
      { label: "Sign-offs Pending", value: "2", sub: "Q2 VAT return", tone: "warning" },
      { label: "Encryption at Rest", value: "AES-256", sub: "Enabled", tone: "success" },
    ],
    filters: ["Search", "Framework", "Owner", "Status"],
    dateRangeFilters: ["Next Due"],
    tableTitle: "Compliance Controls",
    columns: [
      "Control",
      "Framework",
      "Owner",
      "Last Review",
      "Next Due",
      "Evidence",
      "Findings",
      "Status",
    ],
    rows: [
      [
        "ZATCA Phase 2",
        "ZATCA",
        "Finance Mgr",
        "12 May 2026",
        "12 May 2027",
        "CSID + logs",
        "0",
        "Compliant",
      ],
      [
        "Quarterly Access Review",
        "Internal",
        "IT Manager",
        "31 Mar 2026",
        "30 Jun 2026",
        "Report Q2",
        "2 open",
        "Overdue",
      ],
      [
        "Data Retention Policy",
        "ZATCA / GAZT",
        "Legal",
        "01 Jan 2026",
        "01 Jan 2027",
        "Policy v3.2",
        "0",
        "Compliant",
      ],
      [
        "PCI DSS SAQ-C",
        "PCI",
        "IT Manager",
        "20 Apr 2026",
        "20 Apr 2027",
        "SAQ + scans",
        "1 remediated",
        "Compliant",
      ],
      [
        "Change Management",
        "Internal",
        "IT Manager",
        "01 Jul 2026",
        "01 Oct 2026",
        "Change log",
        "0",
        "Compliant",
      ],
    ],
    statusCol: 7,
    actions: ["Review", "Export", "Sign Off"],
    primaryAction: "Add Control",
  },
  {
    path: "/admin/pos-settings",
    group: "Admin",
    title: "POS Settings",
    desc: "Receipt templates, numbering, cash drawer, shift rules, language and offline controls.",
    kpis: [],
    filters: ["Search", "Group", "Scope", "Status"],
    tableTitle: "POS Configuration",
    columns: ["Setting", "Group", "Scope", "Value", "Effective From", "Changed By", "Status"],
    rows: [
      [
        "Receipt Template",
        "Layout",
        "All branches",
        "TMPL-STD-BILINGUAL-v3",
        "01 Jul 2026",
        "admin_ali",
        "Active",
      ],
      [
        "Invoice Numbering",
        "Numbering",
        "Per branch",
        "{BRCODE}-{YYYY}-#####",
        "01 Jan 2026",
        "admin_ali",
        "Active",
      ],
      [
        "Cash Drawer",
        "Hardware",
        "All terminals",
        "Open on payment only",
        "01 Jan 2024",
        "admin_ali",
        "Active",
      ],
      [
        "Shift Open Float",
        "Shift",
        "All terminals",
        "1,000 ر.س default",
        "01 Jan 2024",
        "admin_ali",
        "Active",
      ],
      [
        "Offline Limit",
        "Offline",
        "All terminals",
        "500 tx or 100,000 ر.س",
        "01 Mar 2024",
        "admin_ali",
        "Active",
      ],
      [
        "Language Toggle",
        "Localization",
        "All terminals",
        "EN default, AR available",
        "01 Jan 2024",
        "admin_ali",
        "Active",
      ],
      [
        "Auto Logout",
        "Security",
        "All terminals",
        "10 min idle",
        "01 May 2025",
        "admin_ali",
        "Active",
      ],
    ],
    statusCol: 6,
    actions: ["Configure", "Save", "Rollback", "Audit"],
  },
  {
    path: "/admin/audit-logs",
    group: "Admin",
    title: "Audit Logs",
    desc: "Immutable logs of user, transaction, return, approval, device and configuration events.",
    kpis: [
      { label: "Events Today", value: "4,812", sub: "12 modules", tone: "info" },
      { label: "Critical", value: "4", sub: "Refunds, price override", tone: "warning" },
      { label: "Config Changes", value: "18", sub: "6 admins", tone: "info" },
      { label: "Failed Logins", value: "7", sub: "1 locked", tone: "warning" },
      { label: "Retention", value: "7 years", sub: "Immutable", tone: "success" },
      { label: "Exports (7d)", value: "12", sub: "Auditor role", tone: "info" },
      { label: "Tamper Checks", value: "OK", sub: "Chain valid", tone: "success" },
      { label: "Storage Used", value: "22 GB", sub: "of 100 GB", tone: "info" },
    ],
    filters: ["Search", "Module", "Action", "User", "Branch", "Severity"],
    dateRangeFilters: ["Date"],
    tableTitle: "Audit Trail",
    columns: [
      "Event #",
      "Time",
      "Module",
      "Action",
      "Record",
      "User",
      "Role",
      "Branch",
      "Terminal",
      "Severity",
    ],
    rows: [
      [
        "EV-88412",
        "02:45 PM",
        "POS",
        "Sale Completed",
        "ORD-8092",
        "Fahad Al-Qahtani",
        "Cashier",
        "Riyadh Main",
        "POS-02",
        "Info",
      ],
      [
        "EV-88411",
        "02:44 PM",
        "Returns",
        "Refund > 500 ر.س",
        "RET-224",
        "Ahmed Al-Harbi",
        "Store Manager",
        "Riyadh Main",
        "POS-01",
        "Critical",
      ],
      [
        "EV-88410",
        "02:41 PM",
        "ZATCA",
        "Invoice Failed",
        "INV-2026-00891",
        "system",
        "System",
        "Riyadh Main",
        "POS-01",
        "Critical",
      ],
      [
        "EV-88409",
        "02:33 PM",
        "Pricing",
        "Discount Override 12%",
        "ORD-8087",
        "Ahmed Al-Harbi",
        "Store Manager",
        "Riyadh Main",
        "POS-01",
        "Warning",
      ],
      [
        "EV-88408",
        "02:28 PM",
        "Cashier Shift",
        "Cash In 500 ر.س",
        "SH-1041",
        "Ahmed Al-Harbi",
        "Store Manager",
        "Riyadh Main",
        "POS-01",
        "Info",
      ],
      [
        "EV-88400",
        "02:00 PM",
        "Admin",
        "Setting Changed: Auto Logout",
        "SET-AUTO-LOGOUT",
        "admin_ali",
        "Tenant Admin",
        "HQ",
        "—",
        "Critical",
      ],
    ],
    statusCol: 9,
    actions: ["View Detail", "Filter", "Export"],
  },
  {
    path: "/admin/plans",
    group: "Admin",
    title: "Plans & Pricing",
    desc: "Tenant subscription, feature limits and module entitlements.",
    kpis: [
      {
        label: "Current Plan",
        value: "BuildPOS Enterprise",
        sub: "Renews 12 Dec 2026",
        tone: "success",
      },
      { label: "Terminals", value: "26 / 30", sub: "4 free", tone: "success" },
      { label: "Branches", value: "5 / 10", sub: "5 free", tone: "success" },
      { label: "Users", value: "42 / 50", sub: "8 free", tone: "success" },
      { label: "SKUs", value: "6,412 / 25,000", sub: "Healthy", tone: "success" },
      { label: "Monthly Cost", value: "18,400 ر.س", sub: "+ VAT", tone: "info" },
      { label: "Add-ons", value: "3", sub: "BI, WMS, ZATCA+", tone: "info" },
      { label: "Invoices Paid YTD", value: "6", sub: "All on time", tone: "success" },
    ],
    filters: ["Search", "Entitlement", "Status"],
    tableTitle: "Subscription & Entitlements",
    columns: [
      "Module / Feature",
      "Entitlement",
      "Usage",
      "Limit",
      "Overage Rate",
      "Next Reset",
      "Status",
    ],
    rows: [
      ["Terminals", "Included", 26, 30, "220 ر.س / terminal", "01 Aug 2026", "OK"],
      ["Branches", "Included", 5, 10, "1,200 ر.س / branch", "01 Aug 2026", "OK"],
      ["Users", "Included", 42, 50, "80 ر.س / user", "01 Aug 2026", "OK"],
      ["SKUs", "Included", 6412, 25000, "0.05 ر.س / SKU / mo", "01 Aug 2026", "OK"],
      ["Business Intelligence", "Add-on", "Active", "—", "3,200 ر.س / mo", "01 Aug 2026", "Active"],
      ["Warehouse Mgmt (WMS)", "Add-on", "Active", "—", "2,800 ر.س / mo", "01 Aug 2026", "Active"],
      ["ZATCA+ Advanced", "Add-on", "Active", "—", "1,800 ر.س / mo", "01 Aug 2026", "Active"],
    ],
    statusCol: 6,
    actions: ["Upgrade", "Contact Sales", "Download Invoice"],
  },
  {
    path: "/admin/settings",
    group: "Admin",
    title: "Settings",
    desc: "General system, localization, notification and integration settings.",
    kpis: [],
    filters: ["Group", "Status"],
    tableTitle: "System Settings",
    columns: ["Setting", "Group", "Value", "Last Changed", "Changed By", "Validation", "Status"],
    rows: [
      ["Default Language", "Localization", "English", "01 Jan 2024", "admin_ali", "OK", "Active"],
      ["Currency", "Localization", "SAR", "01 Jan 2024", "admin_ali", "OK", "Active"],
      ["Timezone", "Localization", "Asia/Riyadh", "01 Jan 2024", "admin_ali", "OK", "Active"],
      [
        "Email Provider",
        "Notifications",
        "SES (KSA region)",
        "12 Mar 2026",
        "admin_ali",
        "OK",
        "Active",
      ],
      ["SMS Provider", "Notifications", "Unifonic", "01 Feb 2026", "admin_ali", "OK", "Active"],
      [
        "ERP Integration",
        "Integrations",
        "SAP B1 Cloud",
        "18 Jun 2026",
        "admin_ali",
        "Failed batch",
        "Active",
      ],
      ["SSO", "Security", "SAML 2.0 (Azure AD)", "22 Feb 2026", "admin_ali", "OK", "Active"],
      ["Backup Schedule", "Ops", "Daily 03:00 AST", "01 Jan 2024", "admin_ali", "OK", "Active"],
    ],
    statusCol: 6,
    actions: ["Configure", "Validate", "Save"],
  },
];

export function getModule(pathname: string): ModuleCatalog | undefined {
  return catalog.find((c) => c.path === pathname);
}
